# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: example.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("example.proto", :syntax => :proto3) do
    add_message "Repeated" do
      repeated :foo, :enum, 1, "SomeEnum"
    end
    add_enum "SomeEnum" do
      value :YES, 0
      value :NO, 1
      value :NEVER, 2
    end
  end
end

Repeated = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Repeated").msgclass
SomeEnum = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("SomeEnum").enummodule
